Revert "Add sonarcloud job to CI workflow"
This reverts commit 934df6b235d5bbc3bc44503ca9a59d0f77ef6eaa.

Because of the Error:

```
ERROR: You are running CI analysis while Automatic Analysis is enabled. Please consider disabling one or the other.
```